### ISSUE TITLE
抓包

### ISSUE THREAD

**Issue by cirenyizhiliwo** [ZERO-A-ONE/Beijing-HPV#1]
请问你用的什么抓包的

**Comment by ZERO-A-ONE** [comment]
Fiddler



| |
ZERO-A-ONE
|
|
***@***.***
|




---- Replied mail ----
| From | ***@***.***> |
| Date | 11/29/2021 20:55 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | [ZERO-A-ONE/Beijing-HPV] 抓包 (Issue #1) |

请问你用的什么抓包的

**Comment by BOTAKKK** [comment]
你有成功吗？

**Comment by ZERO-A-ONE** [comment]
> 你有成功吗？

已经上岸，但是不保证现在接口能用，有能力还是二次开发一下

**Comment by cirenyizhiliwo** [comment]
我没成功，不过手工抢号上岸，还是表示谢谢


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ZERO-A-ONE/Beijing-HPV"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月7日(星期二) 晚上8:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ZERO-A-ONE/Beijing-HPV] 抓包 (Issue #1)





  
你有成功吗？
  
已经上岸，但是不保证现在接口能用，有能力还是二次开发一下
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
