### ISSUE TITLE
question

### ISSUE THREAD

**Issue by BOTAKKK** [ZERO-A-ONE/Beijing-HPV#2]
请问一下，是不是只需要修改cookie就可以了，也是顺义妇幼保健院。多谢多谢

**Comment by ZERO-A-ONE** [comment]
> 请问一下，是不是只需要修改cookie就可以了，也是顺义妇幼保健院。多谢多谢

理论上是这样的，但是接口可能会有变化

**Comment by BOTAKKK** [comment]
好的谢谢您，今天晚上试了一下QP.py卡在了获取失败csrf_token，我再尝试看看代码
